name: Publish package to NPM

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install

      # pnpm will run scripts in topological order, ensuring that dependencies
      # are built before dependents. This will also build packages that are
      # irrelevant to the current release, but that's fine.
      - run: pnpm run --recursive build

      - if: startsWith(github.event.release.tag_name, 'ui-react-v')
        working-directory: packages/ui-react
        run: npm publish --provenance --access public
